[package]
name = "hello-wasm-components"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.44.0"
wasi = "0.14.2"

[package.metadata.component]
package = "component:hello-wasm-components"
proxy = true
